title: Programming Languages
author: Nikhil Raikwar
email: raikwarnikhil80@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A programming language is a formal language comprising a set of instructions that produce various kinds of output. Programming languages are used in computer programming to implement algorithms. ... There are programmable machines that use a set of specific instructions, rather than general programming languages.
# social links
twitter_username:NikhilRaikwar2 # DO NOT include the @ character, or else the build will fail!
github_username: NIKHIL165  # DO NOT include the @ character, or else the build will fail!
theme: minima
show_excerpts: true # set to false to remove excerpts on the homepage
